server.port: 8001

rdb:
  driverClassName: org.h2.Driver
  jdbcUrl: "jdbc:h2:file:./db-local;AUTO_SERVER=TRUE"
  username: sa
  password: jpa

server-forward-headers: true

spring.jpa.hibernate:
  jdbc.batch_size: 50
  database-platform: org.hibernate.dialect.H2Dialect
  ddl-auto: update
  naming:
    implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

decorator.datasource.p6spy:
  enable-logging: true
  multiline: true
  logging: slf4j
  log-format: "%(category) | %(executionTime)ms | %(sql)"
